In [51]:
data_copy=data.copy()
data_copy

    CGPA Interactiveness Job Offer
0    9.5             Yes       Yes
1    8.2              No       Yes
2    9.3              No        No
3    7.6              No        No
4    8.4             Yes       Yes
5    9.1             Yes       Yes
6    7.5             Yes        No
7    9.6              No       Yes
8    8.6             Yes       Yes
9    8.3             Yes       Yes
10   9.2             Yes        No
11   8.2             Yes        No
12   8.9             Yes       Yes
13   8.5              No       Yes
14   9.6              No       Yes

In [52]:
X=data_copy[["CGPA","Interactiveness"]]
X

    CGPA Interactiveness
0    9.5             Yes
1    8.2              No
2    9.3              No
3    7.6              No
4    8.4             Yes
5    9.1             Yes
6    7.5             Yes
7    9.6              No
8    8.6             Yes
9    8.3             Yes
10   9.2             Yes
11   8.2             Yes
12   8.9             Yes
13   8.5              No
14   9.6              No

In [53]:
Y=data_copy[["Job Offer"]]
Y

   Job Offer
0        Yes
1        Yes
2         No
3         No
4        Yes
5        Yes
6         No
7        Yes
8        Yes
9        Yes
10        No
11        No
12       Yes
13       Yes
14       Yes

In [54]:
from sklearn.preprocessing import LabelEncoder
interactiveness_le=LabelEncoder()
X.Interactiveness=interactiveness_le.fit_transform(X["Interactiveness"])
X

C:\Users\edwar\AppData\Local\Temp\ipykernel_17652\4008573260.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.Interactiveness=interactiveness_le.fit_transform(X["Interactiveness"])

    CGPA  Interactiveness
0    9.5                1
1    8.2                0
2    9.3                0
3    7.6                0
4    8.4                1
5    9.1                1
6    7.5                1
7    9.6                0
8    8.6                1
9    8.3                1
10   9.2                1
11   8.2                1
12   8.9                1
13   8.5                0
14   9.6                0

In [55]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)
X

array([[ 1.21342187,  0.81649658],
       [-0.75838867, -1.22474487],
       [ 0.9100664 , -1.22474487],
       [-1.66845507, -1.22474487],
       [-0.4550332 ,  0.81649658],
       [ 0.60671094,  0.81649658],
       [-1.82013281,  0.81649658],
       [ 1.36509961, -1.22474487],
       [-0.15167773,  0.81649658],
       [-0.60671094,  0.81649658],
       [ 0.75838867,  0.81649658],
       [-0.75838867,  0.81649658],
       [ 0.30335547,  0.81649658],
       [-0.30335547, -1.22474487],
       [ 1.36509961, -1.22474487]])

In [56]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=.3,random_state=0)

In [57]:
def fit_gaussian_nb(X,Y):
    probab={}
    mean={}
    variance={}
    classes=np.unique(Y)
    for c in classes:
        X_c=X[Y==c]
        probab[c]=len(X_c)/len(X)
        mean[c]=np.mean(X_c,axis=0)
        variance[c]=np.var(X_c,axis=0)
    return probab,mean,variance

def predict_gaussian_nb(X, probab, mean, variance):
    predictions = []
    for x in X:
        class_probabilities = {}
        for c in probab:
            class_probabilities[c] = np.sum(
                np.log(1 / np.sqrt(2 * np.pi * variance[c])) - ((x - mean[c]) ** 2) / (2 * variance[c])) + np.log(
                probab[c])
        predictions.append(max(class_probabilities, key=class_probabilities.get))
    return predictions

In [58]:
probab,mean,variance=fit_gaussian_nb(x_train,y_train.values.ravel())
y_pred=predict_gaussian_nb(x_test,probab,mean,variance)
y_pred

['No', 'No', 'Yes', 'Yes', 'Yes']

In [59]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("CONFUSION MATRIX :\n",cm)
print("ACCURACY SCORE IS ",accuracy_score(y_test,y_pred))

CONFUSION MATRIX :
 [[1 0]
 [1 3]]
ACCURACY SCORE IS  0.8

In [60]:
instance=int(input("ENTER THE NUMBER OF TEST INSTANCES: "))
test_instances=[]
for i in range(instance):
    cgpa=float(input("ENTER CGPA FOR INSTANCE {}: ".format(i+1)))
    interact=input("ENTER INTERACTIVENESS (Yes/No) FOR INSTANCE {}: ".format(i+1))
    interact_encoded=interactiveness_le.transform([interact])[0]
    test_instances.append([cgpa, interact_encoded])

print("TEST INSTANCES :")
for i, instance in enumerate(test_instances):
    print(f"Instance {i+1}: CGPA={instance[0]}, Interactiveness={interactiveness_le.inverse_transform([instance[1]])[0]}")
X_test=sc.transform(test_instances)
y_pred=predict_gaussian_nb(X_test, probab, mean, variance)

print("\nPREDICTIONS :")
for i, pred in enumerate(y_pred):
    print("Instance {}: {}".format(i+1,pred))

TEST INSTANCES :
Instance 1: CGPA=8.5, Interactiveness=No
Instance 2: CGPA=9.0, Interactiveness=No
Instance 3: CGPA=9.5, Interactiveness=No

PREDICTIONS :
Instance 1: No
Instance 2: Yes
Instance 3: Yes

c:\Users\edwar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(